apiVersion: apps/v1
kind: Deployment
metadata:
  name: yaalaoui-playground
  namespace: dev
spec:
  selector:
    matchLabels:
      app: yaalaoui-playground
  template:
    metadata:
      labels:
        app: yaalaoui-playground
    spec:
      containers:
      - image: wil42/playground:v1
        imagePullPolicy: IfNotPresent
        name: yaalaoui-playground
        ports:
        - containerPort: 8888
          name: http
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: yaalaoui-playground
  namespace: dev
  labels:
    run: yaalaoui-playground
spec:
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: yaalaoui-playground
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yaalaoui-playground-ingress
  labels:
    app: yaalaoui-playground
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: yaalaoui-playground
            port:
              number: 8888
